<?php
/**
 * Generated by ninja mod tool to help your favourite ide
 */

// make sure this file does not get used
die();

class Response extends \ninja\Response {}
class Router extends \ninja\Router {}
class User extends \ninja\User {}
class HttpException extends \ninja\HttpException {}
class Tester extends \ninja\Tester {}
class Filter extends \ninja\Filter {}
class Session extends \ninja\Session {}
class Ninja extends \ninja\Ninja {}
class FinderPartials extends \ninja\FinderPartials {}
class Finder extends \ninja\Finder {}
class SchemaValidatorValidLayers extends \ninja\SchemaValidatorValidLayers {}
class Request extends \ninja\Request {}
class View extends \ninja\View {}
class ModStub extends \ninja\ModStub {}
class ModUserModule extends \ninja\ModUserModule {}
class ModUserView extends \ninja\ModUserView {}
class ModUserModel extends \ninja\ModUserModel {}
class ModUserController extends \ninja\ModUserController {}
class ModUserLoginController extends \ninja\ModUserLoginController {}
class ModUserLoginModule extends \ninja\ModUserLoginModule {}
class ModUserLoginModel extends \ninja\ModUserLoginModel {}
class ModUserLoginView extends \ninja\ModUserLoginView {}
class ModPageRootModel extends \ninja\ModPageRootModel {}
class ModPageRedirectModel extends \ninja\ModPageRedirectModel {}
class ModPageController extends \ninja\ModPageController {}
class ModPageView extends \ninja\ModPageView {}
class ModPageModel extends \ninja\ModPageModel {}
class ModPageModule extends \ninja\ModPageModule {}
class ModContainerView extends \ninja\ModContainerView {}
class ModContainerModule extends \ninja\ModContainerModule {}
class ModContainerModel extends \ninja\ModContainerModel {}
class ModContainerExpandableView extends \ninja\ModContainerExpandableView {}
class ModContainerExpandableModel extends \ninja\ModContainerExpandableModel {}
class ModContainerExpandableModule extends \ninja\ModContainerExpandableModule {}
class ModContainerExpandableController extends \ninja\ModContainerExpandableController {}
class ModContainerFallbackModel extends \ninja\ModContainerFallbackModel {}
class ModContainerFallbackModule extends \ninja\ModContainerFallbackModule {}
class ModContainerController extends \ninja\ModContainerController {}
class ModRouter extends \ninja\ModRouter {}
class ModLayerModel extends \ninja\ModLayerModel {}
class ModLayerView extends \ninja\ModLayerView {}
class ModLayerModule extends \ninja\ModLayerModule {}
class ModLayerController extends \ninja\ModLayerController {}
class ModAbstractView extends \ninja\ModAbstractView {}
class ModAbstractController extends \ninja\ModAbstractController {}
class ModAbstractModule extends \ninja\ModAbstractModule {}
class ModAbstractModel extends \ninja\ModAbstractModel {}
class ModReg extends \ninja\ModReg {}
class ModBaseController extends \ninja\ModBaseController {}
class ModBaseIncludeView extends \ninja\ModBaseIncludeView {}
class ModBaseIncludeController extends \ninja\ModBaseIncludeController {}
class ModBaseIncludeModel extends \ninja\ModBaseIncludeModel {}
class ModBaseIncludeModule extends \ninja\ModBaseIncludeModule {}
class ModBaseModel extends \ninja\ModBaseModel {}
class ModBaseView extends \ninja\ModBaseView {}
class ModBaseModule extends \ninja\ModBaseModule {}
class ModBaseCssModel extends \ninja\ModBaseCssModel {}
class ModFileservModule extends \ninja\ModFileservModule {}
class ModFileservModel extends \ninja\ModFileservModel {}
