<?php
/**
 * Generated by ninja mod tool to help your favourite ide
 */

// make sure this file does not get used
die();

class Response extends \ninja\Response {}
class Router extends \ninja\Router {}
class Filter extends \ninja\Filter {}
class Ninja extends \ninja\Ninja {}
class FinderPartials extends \ninja\FinderPartials {}
class Finder extends \ninja\Finder {}
class Request extends \ninja\Request {}
class View extends \ninja\View {}
class ModUserController extends \ninja\ModUserController {}
class ModStatusModel extends \ninja\ModStatusModel {}
class ModUserModuleStatus extends \ninja\ModUserModuleStatus {}
class ModPageController extends \ninja\ModPageController {}
class ModPageModelRoot extends \ninja\ModPageModelRoot {}
class ModPageModelRedirect extends \ninja\ModPageModelRedirect {}
class ModPageModel extends \ninja\ModPageModel {}
class ModPageModule extends \ninja\ModPageModule {}
class ModPageView extends \ninja\ModPageView {}
class ModContainerController extends \ninja\ModContainerController {}
class ModContainerModel extends \ninja\ModContainerModel {}
class ModContainerModule extends \ninja\ModContainerModule {}
class ModContainerView extends \ninja\ModContainerView {}
class ModAbstractController extends \ninja\ModAbstractController {}
class ModAbstractModel extends \ninja\ModAbstractModel {}
class ModAbstractModule extends \ninja\ModAbstractModule {}
class ModAbstractView extends \ninja\ModAbstractView {}
class ModBaseController extends \ninja\ModBaseController {}
class ModBaseIncludeView extends \ninja\ModBaseIncludeView {}
class ModBaseIncludeController extends \ninja\ModBaseIncludeController {}
class ModBaseIncludeModel extends \ninja\ModBaseIncludeModel {}
class ModBaseIncludeModule extends \ninja\ModBaseIncludeModule {}
class ModBaseModel extends \ninja\ModBaseModel {}
class ModBaseView extends \ninja\ModBaseView {}
class ModBaseModule extends \ninja\ModBaseModule {}
class ModBaseCssModel extends \ninja\ModBaseCssModel {}
class ModAdminController extends \ninja\ModAdminController {}
class ModAdminModel extends \ninja\ModAdminModel {}
class ModAdminModule extends \ninja\ModAdminModule {}
class ModAdminView extends \ninja\ModAdminView {}
class ModFileservController extends \ninja\ModFileservController {}
class ModFileservModel extends \ninja\ModFileservModel {}
class ModFileservModule extends \ninja\ModFileservModule {}
class ModFileservView extends \ninja\ModFileservView {}
