<?php

namespace ninja;

class ModPolymerCoreAnimatedpagesController extends \ModPolymerCoreController {

	public static function addPolymerDeps($Asset, $basePath) {

		// unnecessary, empty method
		//parent::addPolymerDeps($Asset, $basePath);

		$Asset
			->addImport(\Finder::joinPath($basePath, 'core-animated-pages/core-animated-pages.html'))
			->addImport(\Finder::joinPath($basePath, 'core-animated-pages/transitions/slide-from-right.html'))
		;

	}

//	public function actionIndex($params = null) {
//		// @TODO: Change the autogenerated code
//		return parent::actionIndex($params);
//	}

}
