<?php

namespace ninja;

class ModPolymerCoreContainerController extends \ModPolymerCoreController {

//	public function actionIndex($params = null) {
//		// @TODO: Change the autogenerated code
//		return parent::actionIndex($params);
//	}


}
