<?php

namespace ninja;

class ModContainerFallbackController extends \ModContainerController {

	public function actionIndex($params = null) {
		// @TODO: Change the autogenerated code
		return parent::actionIndex($params);
	}


}
