<?php

namespace ninja;

class ModPolymerController extends \ModAbstractController {

	public function actionIndex($params = null) {
		// @TODO: Change the autogenerated code
		return parent::actionIndex($params);
	}


}
