<?php

namespace ninja;

class ModPolymerCoreMenuController extends \ModPolymerCoreController {

	/**
	 * I add imports I print in the main template. Call me if your template invokes mine to add my deps
	 */
	public static function addPolymerDeps($Asset, $basePath) {

		$Asset
			->addImport(\Finder::joinPath($basePath, 'core-menu/core-menu.html'))
			->addImport(\Finder::joinPath($basePath, 'paper-item/paper-item.html'))
			->addImport(\Finder::joinPath($basePath, 'core-icon/core-icon.html'));

	}

//	public function actionIndex($params = null) {
//		// @TODO: Change the autogenerated code
//		return parent::actionIndex($params);
//	}


}
