<?php

namespace ninja;

class ModPolymerCoreController extends \ModPolymerController {

	public function actionIndex($params = null) {
		// @TODO: Change the autogenerated code
		return parent::actionIndex($params);
	}

	/**
	 * adds common select code for manipulating the main template
	 * @return $this
	 */
	public static function addJsTemplateSelector($obj) {
		$obj->Asset()
			->addJsCode(
				\ModPageModel::JS_FOOT,
				'var template = document.querySelector(\'template[is="auto-binding"]\')'
			);
	}

}
