<?php

namespace ninja;

class ModNavBarController extends \ModAbstractController {

	public function actionIndex($params = null) {
		// @TODO: Change the autogenerated code
		return parent::actionIndex($params);
	}


}
