<?php

namespace ninja;

class ModNavBarModule extends \ModAbstractModule {

//	public function _beforeRespond($Request) {
//		// @TODO: Change the autogenerated code
//		return parent::_beforeRespond($Request);
//	}

//	public function _respond($Request, $hasShifted) {
//		// @TODO: Change the autogenerated code
//		return parent::_respond($Request, $hasShifted);
//	}

}
