<?php

namespace ninja;

class ModPolymerCoreToolbarController extends \ModPolymerCoreController {

	public static function addPolymerDeps($Asset, $basePath) {

		parent::addPolymerDeps($Asset, $basePath);

		$Asset
			->addImport(\Finder::joinPath($basePath, 'core-toolbar/core-toolbar.html'))
			->addImport(\Finder::joinPath($basePath, 'core-icon-button/core-icon-button.html'))
		;

	}

//	public function actionIndex($params = null) {
//		// @TODO: Change the autogenerated code
//		return parent::actionIndex($params);
//	}

}
