<?php

namespace ninja;

class ModPolymerCoreToolbarController extends \ModPolymerCoreController {

	public function actionIndex($params = null) {
		// @TODO: Change the autogenerated code
		return parent::actionIndex($params);
	}


}
