<?php

namespace ninja;

class ModAdminController extends \ModAbstractController {

	protected $_adminJsTemplates = [
		'require.config({ paths: {"#NAME#": "/assets/admin/js/#NAME#.js"} });',
		'require(["#NAME#"], function(#NAME#) { #NAME#.init(#PARAMS#); });',
	];

	public function actionIndex($params = null) {
		// @TODO: Change the autogenerated code
		return parent::actionIndex($params);
	}

	/**
	 * @param string $name I add a javascript module - load source and execute init()
	 */
	protected function _addAdminJs($name, $params='null') {
		$tr = [
			'#NAME#' => $name,
			'#PARAMS#' => $params,
		];
		foreach ($this->_adminJsTemplates as $eachTemplate) {
			$this->Asset()->addJsCode(
				\ModPageModel::JS_HEAD,
				strtr($eachTemplate, $tr)
			);
		};
	}

}
